name: LineageOS 

on:
  workflow_dispatch:
jobs:
  test:
    name: Build GSIs using foss.crave.io

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps
    - name: Create workspace
      run: mkdir gsi
      continue-on-error: true
    - name: Enter Workspace
      run: cd gsi 
      continue-on-error: true
      # Check-out in order to access the repository's files.
    - name: Check-out to repository
      uses: actions/checkout@v4 
      
    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
        
    - name: Test Local Manifests
      run: |
        git clone https://github.com/RadGoodNowYT/manifest.git --depth 1 .repo/local_manifests && \
        timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
        rm -rf .repo
      timeout-minutes: 10    
    - name: Exports
      run: |
        export BUILD_HOSTNAME=build
        export BUILD_USERNAME=builder
    - name: Run Script
      run: bash build.sh
      # Only reach this when the user killed the workflow.
    - name: Execute if the job is cancelled
      if: ${{ cancelled() }}
      run: crave stop --all
    - name: Find output file
      run: |
        mv */system.img LineageOS-19.1-P682LPN-$(date +%Y%m%d).img
        mv system.img LineageOS-19.1-P682LPN-$(date +%Y%m%d).img
        xz -z -k LineageOS*.img
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          *.img.xz
        name: RisingOS-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Target: RisingOS-Generic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
